In [1]:

# get_data
import pandas as pd
import torch
df=pd.read_csv('/home/ubuntu/project/mayang/Classification/process_data/tpcds/tpcds_99.csv')
df.head()

Unnamed: 0                                              query  \
0           0  with customer_total_return as\n(select sr_cust...   
1           1  with customer_total_return as\n(select sr_cust...   
2           2  with customer_total_return as\n(select sr_cust...   
3           3  with customer_total_return as\n(select sr_cust...   
4           4  \n\n-- end workload 1 in stream 0 using templa...   

                                               index  
0                    ['I(C customer.c_customer_id)']  
1  ['I(C customer.c_customer_id)', 'I(C date_dim....  
2                           ['I(C date_dim.d_year)']  
3                                                 []  
4                           ['I(C date_dim.d_year)']

In [2]:
# def read_queries_from_file(sql_file):
#     with open(sql_file, 'r', encoding='utf-8') as file:
#         # 读取整个文件内容
#         sql_content = file.read()
        
#         # 按照 ';' 分割成独立的 SQL 语句
#         queries = [query.strip() for query in sql_content.split(';') if query.strip()]
        
#     return queries

# # 使用示例
# sql_file = '/home/ubuntu/project/mayang/Classification/process_data/tpcds/unique_queries_sorted_by_id.sql'
# queries_list = read_queries_from_file(sql_file)
# len(queries_list)

In [3]:
queries_list=df['query'].values
sql_query=queries_list[5000]

In [4]:
from sql import Sql,_global
from core import database, Sql, Plan, load

sql_graphs=[]
database.setup(dbname='indexselection_tpcds___1 ', user='postgres', password='password', host='127.0.0.1', port='5432', cache=False)
# print(sql_query)

sql_instance = Sql(sql_query)
# 构建异构图
g, data_dict, node_indexes, _ = sql_instance.to_hetero_graph_dgl()
     
#combined_features
#node
filter_features = g.ndata['filter']
edge_features = g.ndata['edge']
onehot_features = g.ndata['onehot']
others_features = g.ndata['others'].view(g.ndata['filter'].shape[0], -1)

# 假设两个特征的维度是相同的
combined_features = torch.cat((filter_features,edge_features, onehot_features,others_features), dim=1)
g.ndata['feature'] = combined_features
# edge
num_edge_features = 4
edge_features = torch.randn(g.num_edges(), num_edge_features)
g.edata['feature'] = edge_features

Current working directory: /home/ubuntu/project/mayang/LOGER/core
['/home/ubuntu/project/mayang/LOGER/core', '/home/ubuntu/anaconda3/envs/test/lib/python38.zip', '/home/ubuntu/anaconda3/envs/test/lib/python3.8', '/home/ubuntu/anaconda3/envs/test/lib/python3.8/lib-dynload', '', '/home/ubuntu/.local/lib/python3.8/site-packages', '/home/ubuntu/anaconda3/envs/test/lib/python3.8/site-packages', '/home/ubuntu/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/_vendor']
Current working directory: /home/ubuntu/project/mayang/LOGER
['/home/ubuntu/project/mayang/LOGER/core', '/home/ubuntu/anaconda3/envs/test/lib/python38.zip', '/home/ubuntu/anaconda3/envs/test/lib/python3.8', '/home/ubuntu/anaconda3/envs/test/lib/python3.8/lib-dynload', '', '/home/ubuntu/.local/lib/python3.8/site-packages', '/home/ubuntu/anaconda3/envs/test/lib/python3.8/site-packages', '/home/ubuntu/anaconda3/envs/test/lib/python3.8/site-packages/setuptools/_vendor']
{'dbname': 'indexselection_tpcds___1 ', 'user': 'post

KeyError: 'sr_items'

In [5]:
g

NameError: name 'g' is not defined

In [41]:
g.edges()

(tensor([0, 3, 0, 3, 0, 2, 3, 1, 0, 3, 0, 4]),
 tensor([3, 0, 3, 0, 2, 0, 1, 3, 3, 0, 4, 0]))

In [42]:
g.edata['feature'].shape,g.edata['feature']

(torch.Size([12, 4]),
 tensor([[-0.2075,  1.2220,  1.6008, -0.6965],
         [ 0.4395,  0.0185,  0.5346,  2.3665],
         [-2.7848, -0.3393,  0.5582,  1.3233],
         [-0.5969, -0.6648,  0.3867,  1.1314],
         [-1.6247, -0.1700, -0.3397, -0.7721],
         [ 0.0426, -0.5491,  0.9058,  0.1493],
         [-0.9375,  0.2992,  2.1292,  0.1295],
         [ 0.9437,  0.2782,  2.4661, -0.9250],
         [ 0.1810, -0.4363, -0.3841,  0.9523],
         [-1.2513, -0.9939,  1.9758, -2.0835],
         [ 0.0512, -0.8343,  0.6060,  1.0975],
         [ 0.6144,  0.3288, -0.2207,  0.3295]]))

In [6]:
queries_list=list(set(queries_list))

In [7]:
from sql import Sql,_global
from core import database, Sql, Plan, load

sql_graphs = []
cnt = 0

for sql_query in queries_list:
    try:
        print(sql_query)
        if cnt % 10 == 0:
            print(cnt)
        
        # 创建 Sql 实例并构建异构图
        sql_instance = Sql(sql_query)
        g, data_dict, node_indexes, _ = sql_instance.to_hetero_graph_dgl()
        
     #    # Node features
     #    filter_features = g.ndata['filter']
     #    edge_features = g.ndata['edge']
     #    onehot_features = g.ndata['onehot']
     #    others_features = g.ndata['others'].view(g.ndata['filter'].shape[0], -1)

     #    # Combine features (假设特征维度相同)
     #    combined_features = torch.cat((filter_features, edge_features, onehot_features, others_features), dim=1)
     #    g.ndata['feature'] = combined_features
        
     #    # Edge features
     #    num_edge_features = 4
     #    edge_features = torch.randn(g.num_edges(), num_edge_features)
     #    g.edata['feature'] = edge_features
        
     #    # Append the graph to the list
     #    sql_graphs.append(g)
        cnt += 1

    except Exception as e:
        print(f"Error processing query: {sql_query}. Skipping. Error: {e}")
        continue



-- end workload 50 in stream 0 using template query50.tpl


WITH web_v1 as (
select
  ws_item_sk item_sk, d_date,
  sum(sum(ws_sales_price))
      over (partition by ws_item_sk order by d_date rows between unbounded preceding and current row) cume_sales
from web_sales
    ,date_dim
where ws_sold_date_sk=d_date_sk
  and d_month_seq between 1212 and 1212+11
  and ws_item_sk is not NULL
group by ws_item_sk, d_date),
store_v1 as (
select
  ss_item_sk item_sk, d_date,
  sum(sum(ss_sales_price))
      over (partition by ss_item_sk order by d_date rows between unbounded preceding and current row) cume_sales
from store_sales
    ,date_dim
where ss_sold_date_sk=d_date_sk
  and d_month_seq between 1212 and 1212+11
  and ss_item_sk is not NULL
group by ss_item_sk, d_date)
 select  *
from (select item_sk
     ,d_date
     ,web_sales
     ,store_sales
     ,max(web_sales)
         over (partition by item_sk order by d_date rows between unbounded preceding and current row) web_cumulative
     ,max

In [8]:
cnt

22

In [5]:
import torch_geometric

data = torch_geometric.utils.from_dgl(g)

data

Data(edge_index=[2, 12], filter=[5, 34], filter_mask=[5, 34], edge=[5, 34], global=[5, 1], onehot=[5, 25], others=[5, 34, 13], feature=[12, 4])

In [6]:
# torch_geometric
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import TransformerConv, TopKPooling
from torch_geometric.nn import global_mean_pool as gap, global_max_pool as gmp

class GraphEncode(nn.Module):
    def __init__(self, in_feats, edge_feats, out_feats):
        super(GraphEncode, self).__init__()
        
        self.embedding_size = 64  # 嵌入层维度
        self.n_heads = 4  # 注意力头数
        self.dropout_rate = 0.5
        self.top_k_ratio = 0.5
        self.top_k_every_n = 1
        self.dense_neurons = 128
        self.edge_dim = edge_feats
        
        # 初始化 TransformerConv 层
        self.conv1 = TransformerConv(
            in_feats, 
            self.embedding_size, 
            heads=self.n_heads, 
            dropout=self.dropout_rate,
            edge_dim=self.edge_dim,
            beta=True
        )
        self.transf1 = nn.Linear(self.embedding_size * self.n_heads, self.embedding_size)
        self.bn1 = nn.BatchNorm1d(self.embedding_size)

        # 定义后续的 TransformerConv 层
        self.conv_layers = nn.ModuleList()
        self.transf_layers = nn.ModuleList()
        self.bn_layers = nn.ModuleList()
        self.pooling_layers = nn.ModuleList()

        for _ in range(3):  # 使用 3 层
            self.conv_layers.append(TransformerConv(
                self.embedding_size, 
                self.embedding_size, 
                heads=self.n_heads, 
                dropout=self.dropout_rate,
                edge_dim=self.edge_dim,
                beta=True
            ))
            self.transf_layers.append(nn.Linear(self.embedding_size * self.n_heads, self.embedding_size))
            self.bn_layers.append(nn.BatchNorm1d(self.embedding_size))
            self.pooling_layers.append(TopKPooling(self.embedding_size, ratio=self.top_k_ratio))

    def forward(self, x, edge_attr, edge_index, batch_index):
        print(f"x shape: {x.shape}")
        print(f"edge_attr shape: {edge_attr.shape}")
        # 初始卷积层
        x = self.conv1(x, edge_index, edge_attr)
        x = torch.relu(self.transf1(x))
        x = self.bn1(x)

        global_representation = []
        
        for i, conv_layer in enumerate(self.conv_layers):
            x = conv_layer(x, edge_index, edge_attr)
            x = torch.relu(self.transf_layers[i](x))
            x = self.bn_layers[i](x)
            
            # 聚合图表示
            if i % self.top_k_every_n == 0 or i == len(self.conv_layers) - 1:
                x, edge_index, edge_attr, batch_index, _, _ = self.pooling_layers[i](
                    x, edge_index, edge_attr, batch_index
                )
                global_representation.append(torch.cat([
                    gmp(x, batch_index), 
                    gap(x, batch_index)
                ], dim=1))

        x = sum(global_representation)
        
        return x

class TimePredictionModel(nn.Module):
    def __init__(self, in_feats, edge_feats, out_feats):
        super(TimePredictionModel, self).__init__()
        self.graph_encoder = GraphEncode(in_feats, edge_feats, out_feats)
        self.fc = nn.Linear(2 * 64, 1)  # 2 * 64 是因为我们在全局池化时合并了 mean 和 max 结果
    
    def forward(self, x, edge_attr, edge_index, batch_index):
        graph_embedding = self.graph_encoder(x, edge_attr, edge_index, batch_index)
        return self.fc(graph_embedding)

In [9]:
import torch
from torch_geometric.data import Data
import dgl

def dgl_to_pyg(dgl_graph):
    # 从 DGL 图获取信息
    x = dgl_graph.ndata['feature']  # 节点特征
    edge_index = dgl_graph.edges()  # 边索引
    edge_attr = dgl_graph.edata['feature']  # 边特征
    batch = torch.zeros(dgl_graph.number_of_nodes(), dtype=torch.long)  # 默认所有节点在同一图中

    # 转换边索引为 PyG 格式
    edge_index = torch.stack(edge_index).long()

    # 创建 PyG Data 对象
    pyg_data = Data(x=x, edge_index=edge_index, edge_attr=edge_attr, batch=batch)
    return pyg_data

sql_graphs_pyg = []

database.setup(dbname='indexselection_tpcds___1', user='postgres', password='password', host='127.0.0.1', port='5432', cache=False)
cnt = 1

for sql_query in df['query'].values[5000:5050]:
    # print(sql_query)
    if cnt % 10 == 0:
        print(cnt)

    sql_instance = Sql(sql_query)
    # 构建异构图
    g, data_dict, node_indexes = sql_instance.to_hetero_graph_dgl()
    
    # combined_features
    # node
    filter_features = g.ndata['filter']
    edge_features = g.ndata['edge']
    onehot_features = g.ndata['onehot']
    others_features = g.ndata['others'].view(g.ndata['filter'].shape[0], -1)

    # 假设两个特征的维度是相同的
    combined_features = torch.cat((filter_features, edge_features, onehot_features, others_features), dim=1)
    g.ndata['feature'] = combined_features

    # edge
    num_edge_features = 4
    edge_features = torch.randn(g.num_edges(), num_edge_features)
    g.edata['feature'] = edge_features

    # 转换为 PyG 数据对象
    pyg_data = dgl_to_pyg(g)
    sql_graphs_pyg.append(pyg_data)
    
    cnt += 1

{'dbname': 'indexselection_tpcds___1', 'user': 'postgres', 'password': 'password', 'host': '127.0.0.1', 'port': '5432', 'cache': False}
<connection object at 0x7f7ad9d7aa40; dsn: 'user=postgres password=xxx dbname=indexselection_tpcds___1 host=127.0.0.1 port=5432', closed: 0>
<cursor object at 0x7f7ad9bd4a90; closed: 0>
10
20
30
40
50


In [10]:
from torch_geometric.loader import DataLoader

# 创建 PyG DataLoader
data_loader = DataLoader(sql_graphs_pyg, batch_size=32, shuffle=True)

# 初始化模型和优化器
model_params = {
    "model_embedding_size": 64,
    "model_attention_heads": 4,
    "model_layers": 3,
    "model_dropout_rate": 0.5,
    "model_top_k_ratio": 0.5,
    "model_top_k_every_n": 1,
    "model_dense_neurons": 128,
    "model_edge_dim": num_edge_features
}

num_node_features=535
model = TimePredictionModel(num_node_features, num_edge_features, 64)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
criterion = torch.nn.MSELoss()

# 训练循环
for epoch in range(10):
    model.train()
    total_loss = 0
    for batch in data_loader:
        # 前向传播
        pred_time = model(batch.x, batch.edge_attr, batch.edge_index, batch.batch)
        
        # 假设目标是生成随机数据，你需要用实际的目标数据替换
        target = torch.randn(pred_time.size(0), 1, dtype=torch.float)
        
        # 计算损失
        loss = criterion(pred_time, target)

        # 反向传播和优化
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f'Epoch {epoch + 1}, Loss: {total_loss:.4f}')

x shape: torch.Size([160, 535])
edge_attr shape: torch.Size([384, 4])
x shape: torch.Size([90, 535])
edge_attr shape: torch.Size([216, 4])
Epoch 1, Loss: 3.1244
x shape: torch.Size([160, 535])
edge_attr shape: torch.Size([384, 4])
x shape: torch.Size([90, 535])
edge_attr shape: torch.Size([216, 4])
Epoch 2, Loss: 3.2408
x shape: torch.Size([160, 535])
edge_attr shape: torch.Size([384, 4])
x shape: torch.Size([90, 535])
edge_attr shape: torch.Size([216, 4])
Epoch 3, Loss: 3.0698
x shape: torch.Size([160, 535])
edge_attr shape: torch.Size([384, 4])
x shape: torch.Size([90, 535])
edge_attr shape: torch.Size([216, 4])
Epoch 4, Loss: 4.1760
x shape: torch.Size([160, 535])
edge_attr shape: torch.Size([384, 4])
x shape: torch.Size([90, 535])
edge_attr shape: torch.Size([216, 4])
Epoch 5, Loss: 2.7699
x shape: torch.Size([160, 535])
edge_attr shape: torch.Size([384, 4])
x shape: torch.Size([90, 535])
edge_attr shape: torch.Size([216, 4])
Epoch 6, Loss: 3.4776
x shape: torch.Size([160, 535])
ed

In [ ]:
import torch
filter_features = g.ndata['filter']
edge_features = g.ndata['edge']
onehot_features = g.ndata['onehot']
others_features = g.ndata['others'].view(g.ndata['onehot'].shape[0], -1)

print(filter_features.shape,onehot_features.shape,others_features.shape)
# 假设两个特征的维度是相同的
combined_features = torch.cat((filter_features,edge_features, onehot_features,others_features), dim=1)
g.ndata['feature'] = combined_features
combined_features.shape

torch.Size([5, 34]) torch.Size([5, 25]) torch.Size([5, 442])


torch.Size([5, 535])

In [ ]:
g.ndata['feature'].shape,g.edata['feature'].shape

(torch.Size([5, 535]), torch.Size([12, 4]))

In [ ]:
execution_times=[torch.tensor(x, dtype=torch.float32) for x in df['t1'].values[5000:5050]]

In [ ]:
g.edata['feature'].dtype

torch.float32